# Generated by Django 3.0.7 on 2020-06-04 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=300)),
                ('prenom', models.CharField(max_length=300)),
                ('tel', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('cnss', models.CharField(blank=True, max_length=300)),
                ('ancien', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'beneficiaires',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'devises',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'entreprises',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'filieres',
            },
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('theme', models.CharField(max_length=300)),
                ('lieu', models.CharField(max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_depot', models.DateField()),
                ('date_demarrage', models.DateField()),
                ('date_achevement', models.DateField()),
                ('montant', models.FloatField()),
                ('competence', models.CharField(max_length=300, null=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Devise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Entreprise')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Filiere')),
            ],
            options={
                'db_table': 'formulaires',
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'operateurs',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'secteurs',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=300)),
                ('horaire', models.IntegerField(default=0)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.Formulaire')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.AddField(
            model_name='formulaire',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Operateur'),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Secteur'),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filiere',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.Secteur'),
        ),
        migrations.CreateModel(
            name='CreditAlloue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe', models.IntegerField()),
                ('fc', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_alloue', to='core.Filiere')),
            ],
            options={
                'db_table': 'credit_alloues',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaireFormulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=300)),
                ('profil_bareme', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('contrat', models.CharField(max_length=10)),
                ('beneficier', models.BooleanField(default=False)),
                ('non_conforme', models.BooleanField(default=False)),
                ('engagement', models.FloatField()),
                ('consommation', models.FloatField()),
                ('date_dembauche', models.DateField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Beneficiaire')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Formulaire')),
            ],
            options={
                'db_table': 'beneficiaire_formulaires',
            },
        ),
    ]
