# Generated by Django 3.0.7 on 2020-06-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facture',
            table='facturations',
        ),
    ]
