# Generated by Django 3.0.7 on 2020-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200605_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taux',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_dh',
            field=models.FloatField(default=0),
        ),
    ]
