# Generated by Django 3.0.7 on 2020-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200603_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'operateurs',
            },
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='raison_sociale',
            field=models.CharField(max_length=300),
        ),
    ]
