# Generated by Django 3.0.7 on 2020-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200605_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='ancien',
            field=models.BooleanField(default=True),
        ),
    ]
