# Generated by Django 3.0.7 on 2020-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateur',
            old_name='operateur',
            new_name='libelle',
        ),
    ]
