# Generated by Django 3.0.7 on 2020-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200605_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaireformulaire',
            name='consommation',
            field=models.FloatField(default=0),
        ),
    ]
