# Generated by Django 3.0.7 on 2020-06-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200603_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateur',
            old_name='libelle',
            new_name='operateur',
        ),
    ]
