# Generated by Django 3.0.7 on 2020-06-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200603_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'devises',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'secteurs',
            },
        ),
    ]
