# Generated by Django 3.0.7 on 2020-06-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_devise_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=300)),
                ('secteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.Secteur')),
            ],
            options={
                'db_table': 'filieres',
            },
        ),
    ]
