# Generated by Django 3.0.7 on 2020-06-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200605_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='formulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='core.Formulaire'),
        ),
    ]
