# Generated by Django 3.0.7 on 2020-06-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiere',
            old_name='secteur_id',
            new_name='secteur',
        ),
    ]
