# Generated by Django 3.0.7 on 2020-06-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200603_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAlloue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe', models.IntegerField()),
                ('fc', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_alloue', to='core.Filiere')),
            ],
            options={
                'db_table': 'credit_alloues',
            },
        ),
    ]
