# Generated by Django 3.0.7 on 2020-06-04 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_creditalloue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('theme', models.CharField(max_length=300)),
                ('lieu', models.CharField(max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_depot', models.DateField()),
                ('date_demarrage', models.DateField()),
                ('date_achevement', models.DateField()),
                ('montant', models.FloatField()),
                ('competence', models.CharField(max_length=300, null=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Devise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Entreprise')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Filiere')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Operateur')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Secteur')),
            ],
            options={
                'db_table': 'formulaires',
            },
        ),
    ]
