# Generated by Django 3.0.7 on 2020-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200606_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=None),
        ),
    ]
