# Generated by Django 3.0.7 on 2020-06-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200609_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='user',
        ),
    ]
