# Generated by Django 3.0.7 on 2020-06-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_facture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='user',
        ),
    ]
