# Generated by Django 3.0.7 on 2020-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=300)),
                ('prenom', models.CharField(max_length=300)),
                ('tel', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('cnss', models.CharField(blank=True, max_length=300)),
                ('ancien', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'beneficiaires',
            },
        ),
    ]
