# Generated by Django 3.0.7 on 2020-06-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200609_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='user',
        ),
    ]
