# Generated by Django 3.0.7 on 2020-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200609_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
