# Generated by Django 3.0.7 on 2020-06-12 07:26

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=300)),
                ('prenom_employe', models.CharField(max_length=300)),
                ('tel', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(null=True, upload_to=core.models.user_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employes',
            },
        ),
    ]
