# Generated by Django 3.0.7 on 2020-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200612_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='agence',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
