# Generated by Django 3.0.7 on 2020-06-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_employe_agence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomeFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=100)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diplome_filiere', to='core.Filiere')),
            ],
            options={
                'db_table': 'diplome_filieres',
            },
        ),
    ]
